"""
AquaGuard-X
AquaIntel Output Validator

Validates the final decision produced by
the AquaIntel decision-fusion layer.
"""


VALID_STATUSES = {
    "NORMAL",
    "CAUTION",
    "WARNING",
    "CRITICAL"
}


def validate_output(
    rule_result,
    svm_result,
    fusion_result
):
    """
    Validate the combined AquaIntel decision.

    Deterministic safety rules have highest priority.
    """

    rule_status = rule_result.get(
        "status",
        "NORMAL"
    )

    svm_prediction = svm_result.get(
        "prediction",
        "NORMAL"
    )

    svm_confidence = float(
        svm_result.get(
            "confidence",
            0.0
        )
    )

    proposed_status = fusion_result.get(
        "status",
        "NORMAL"
    )

    corrections = []

    # --------------------------------------------------
    # Basic status validation
    # --------------------------------------------------

    if proposed_status not in VALID_STATUSES:

        corrections.append(
            "Invalid status generated by decision fusion."
        )

        proposed_status = "CAUTION"

    # --------------------------------------------------
    # Safety rule: CRITICAL cannot be downgraded
    # --------------------------------------------------

    if rule_status == "CRITICAL":

        if proposed_status != "CRITICAL":

            corrections.append(
                "Critical rule violation cannot be downgraded."
            )

        proposed_status = "CRITICAL"

    # --------------------------------------------------
    # Safety rule: WARNING cannot become NORMAL
    # --------------------------------------------------

    elif rule_status == "WARNING":

        if proposed_status == "NORMAL":

            corrections.append(
                "Known rule violation prevents NORMAL status."
            )

            proposed_status = "WARNING"

    # --------------------------------------------------
    # ML anomaly without known rule violation
    # --------------------------------------------------

    elif (
        rule_status == "NORMAL"
        and svm_prediction == "ANOMALY"
    ):

        if proposed_status == "NORMAL":

            corrections.append(
                "SVM anomaly requires further review."
            )

            proposed_status = "CAUTION"

    # --------------------------------------------------
    # Confidence validation
    # --------------------------------------------------

    if svm_confidence < 0.0:

        svm_confidence = 0.0

        corrections.append(
            "SVM confidence was below valid range."
        )

    elif svm_confidence > 1.0:

        svm_confidence = 1.0

        corrections.append(
            "SVM confidence exceeded valid range."
        )

    # --------------------------------------------------
    # Validation decision
    # --------------------------------------------------

    if corrections:

        validation_decision = "CORRECTED"
        agreement = False

    else:

        validation_decision = "ACCEPT"
        agreement = True

    return {
        "status": proposed_status,
        "agreement": agreement,
        "decision": validation_decision,
        "corrections": corrections,
        "svm_confidence": round(
            svm_confidence,
            4
        )
    }